ci:
  skip:
    # Skip the copyright check on pre-commit.ci because we don't have the Git history
    - copyright
    - copyright-required

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=125"]
        types: [file, python]

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--line-length=125", "--profile=black"]
        types: [file, python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=125", "--max-complexity=10"]
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args:
          [
            "--max-line-length=125",
            "--in-place"
          ]
        types: [file, python]

  - repo: https://github.com/sbrunner/hooks
    rev: 1.6.1
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed
          )$
