# Copyright 2023-2024 Amazon.com, Inc. or its affiliates.

version: "3.8"
services:
  tile-server-integ:
    build:
      context: ..
      dockerfile: docker/Dockerfile.integ
    container_name: "osml-tile-server-test-integ"
    user: root
    ports:
      - '8080:8080'
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_LAMBDA_RUNTIME_API="localhost"
    volumes:
      - "/tmp/local_viewpoint_cache:/tmp/viewpoint:rw"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - SYS_PTRACE
