# Copyright 2024 Amazon.com, Inc. or its affiliates.

name: tile_server_test
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11.6
  - conda-forge::boto3=1.34.99
  - conda-forge::proj=9.3.1
  - conda-forge::pip=24.0
  - conda-forge::hilbertcurve
  - numpy
  - requests
  - pip:
      - geojson==3.1.0
      - pytest==7.3.1
      - python-json-logger==2.0.7
