# Copyright 2024 Amazon.com, Inc. or its affiliates.

name: tile_server_test
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11
  - conda-forge::boto3=1.35
  - conda-forge::proj=9.5
  - conda-forge::pip=24.2
  - conda-forge::hilbertcurve
  - numpy
  - requests
  - pip:
      - geojson==3.1
      - python-json-logger==2.0
